apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-service
  name: identity-service
spec:
  ports:
  - name: "5051"
    port: 5051
    targetPort: 5051
  selector:
    io.kompose.service: identity-service
status:
  loadBalancer: {}
